#define MN_Object_String 43
#define MN_boolean_opNOT 28
#define MN_boolean_opEQ 24
#define MN_boolean_opNEQ 25
#define MN_boolean_box 56
#define MN_int_opSUB 19
#define MN_int_opADD 18
#define MN_int_opSUB 19
#define MN_int_opMUL 17
#define MN_int_opDIV 15
#define MN_int_opMOD 16
#define MN_int_opEQ 24
#define MN_int_opNEQ 25
#define MN_int_opLT 20
#define MN_int_opLTE 21
#define MN_int_opGT 22
#define MN_int_opGTE 23
#define MN_int_String 43
#define MN_int_box 56
#define MN_String_opEQ 24
#define MN_String_opNEQ 25
#define MN_String_int 34
#define MN_String_opADD 18
#define MN_Func_new 40
#define MN_Func_invoke 57
#define MN_System_assert 58
#define MN_System_p 59
#define MN_System_gc 61
#define MN_NameSpace_import 62
#define MN_NameSpace_load 64

#define TY_float 22

#define MN_int_opADD 18
#define MN_int_opSUB 19
#define MN_int_opMUL 17
#define MN_int_opDIV 15
#define MN_int_opEQ 24
#define MN_int_opNEQ 25
#define MN_int_opLT 20
#define MN_int_opLTE 21
#define MN_int_opGT 22
#define MN_int_opGTE 23
#define MN_int_float 68
#define MN_String_float 68
#define MN_float_opADD 18
#define MN_float_opADD 18
#define MN_float_opSUB 19
#define MN_float_opMUL 17
#define MN_float_opDIV 15
#define MN_float_opEQ 24
#define MN_float_opNEQ 25
#define MN_float_opLT 20
#define MN_float_opLTE 21
#define MN_float_opGT 22
#define MN_float_opGTE 23
#define MN_float_int 34
#define MN_float_String 43
#define MN_float_opSUB 19

#define MN_Array_get 0
#define MN_Array_set 0
#define MN_Array_removeAt 75
#define MN_Array_getSize 76
#define MN_Array_getlength 77
#define MN_Array_add 78
#define MN_Array_push 79
#define MN_Array_pop 80
#define MN_Array_shift 81
#define MN_Array_unshift 82
#define MN_Array_reverse 83
#define MN_Array_concat 84
#define MN_Array_indexOf 86
#define MN_Array_lastIndexOf 87
#define MN_Array_String 43
#define MN_Array_new 40
#define MN_Array_newArray 89
#define MN_Array_newList 90

#define MN_System_balanceControl 92
#define MN_System_balanceInit 93
#define MN_System_dly 94
#define MN_System_actMainTask 95
#define MN_System_ecrobotIsRunning 96
#define MN_System_tailControl 97
#define MN_System_manipulateTail 98
#define MN_System_ecrobotInitNxtstate 99
#define MN_System_ecrobotInitSensors 100
#define MN_System_ecrobotSetLightSensorActive 101
#define MN_System_ecrobotGetGyroSensor 102
#define MN_System_ecrobotGetLightSensor 103
#define MN_System_nxtMotorSetSpeed 104
#define MN_System_nxtMotorSetCount 105
#define MN_System_nxtMotorGetCount 106
#define MN_System_staCyc 107
#define MN_System_waiSem 108
#define MN_System_ecrobotGetSonarSensor 109

