#define TY_void 0
#define TY_var 1
#define TY_Object 2
#define TY_boolean 3
#define TY_int 4
#define TY_String 5
#define TY_Array 6
#define TY_Param 7
#define TY_Method 8
#define TY_Func 9
#define TY_System 10
#define TY_0 11
#define TY_BasicBlock 12
#define TY_ByteCode 13
#define TY_NameSpace 14
#define TY_Token 15
#define TY_Expr 16
#define TY_Stmt 17
#define TY_Block 18
#define TY_Gamma 19

#define MN_Object_String 49195
#define MN_boolean_opNOT 28
#define MN_boolean_opEQ 24
#define MN_boolean_opNEQ 25
#define MN_boolean_box 56
#define MN_int_opSUB 19
#define MN_int_opADD 18
#define MN_int_opSUB 19
#define MN_int_opMUL 17
#define MN_int_opDIV 15
#define MN_int_opMOD 16
#define MN_int_opEQ 24
#define MN_int_opNEQ 25
#define MN_int_opLT 20
#define MN_int_opLTE 21
#define MN_int_opGT 22
#define MN_int_opGTE 23
#define MN_int_String 49195
#define MN_int_box 56
#define MN_String_opEQ 24
#define MN_String_opNEQ 25
#define MN_String_int 49186
#define MN_String_opADD 18
#define MN_Func_new 40
#define MN_Func_invoke 57
#define MN_System_assert 58
#define MN_System_p 59
#define MN_System_gc 61
#define MN_NameSpace_import 62
#define MN_NameSpace_load 64

#define TY_float 22

#define MN_int_opADD 18
#define MN_int_opSUB 19
#define MN_int_opMUL 17
#define MN_int_opDIV 15
#define MN_int_opEQ 24
#define MN_int_opNEQ 25
#define MN_int_opLT 20
#define MN_int_opLTE 21
#define MN_int_opGT 22
#define MN_int_opGTE 23
#define MN_int_float 49220
#define MN_String_float 49220
#define MN_float_opADD 18
#define MN_float_opADD 18
#define MN_float_opSUB 19
#define MN_float_opMUL 17
#define MN_float_opDIV 15
#define MN_float_opEQ 24
#define MN_float_opNEQ 25
#define MN_float_opLT 20
#define MN_float_opLTE 21
#define MN_float_opGT 22
#define MN_float_opGTE 23
#define MN_float_int 49186
#define MN_float_String 49195
#define MN_float_opSUB 19


#define MN_Array_get 16384
#define MN_Array_set 8192
#define MN_Array_removeAt 75
#define MN_Array_getSize 16460
#define MN_Array_getlength 16461
#define MN_Array_add 78
#define MN_Array_push 79
#define MN_Array_pop 80
#define MN_Array_shift 81
#define MN_Array_unshift 82
#define MN_Array_reverse 83
#define MN_Array_concat 84
#define MN_Array_indexOf 86
#define MN_Array_lastIndexOf 87
#define MN_Array_String 49195
#define MN_Array_new 40
#define MN_Array_newArray 89
#define MN_Array_newList 90

#define TY_NXT 24

#define MN_NXT_init 95
#define MN_NXT_ecrobotIsRunning 96
#define MN_NXT_tailControl 97
#define MN_NXT_manipulateTail 98
#define MN_NXT_ecrobotGetGyroSensor 99
#define MN_NXT_ecrobotGetLightSensor 100
#define MN_NXT_getsonarSensor 16485
#define MN_NXT_updateStatus 102
#define MN_NXT_balancePid 103
#define MN_NXT_balance 104
#define MN_NXT_tailwalk 105
#define MN_NXT_tailwalkPid 106
#define MN_NXT_getgrayFlag 16491
#define MN_NXT_soundTone 108
#define MN_NXT_getgyroOffset 16493
#define MN_NXT_setgyroOffset 8301
#define MN_NXT_gettail 16494
#define MN_NXT_settail 8302
#define MN_NXT_getdistance 16495
#define MN_NXT_setdistance 8303
#define MN_NXT_gettimer 16496
#define MN_NXT_cleartimer 113
#define MN_NXT_gettheta 16498
#define MN_NXT_cleartheta 115
#define MN_NXT_getlight 16500
#define MN_NXT_gettargetLight 16501
#define MN_NXT_settargetLight 8309
#define MN_NXT_resetMotor 118
#define MN_NXT_tailwalkWithBottle 119
#define MN_NXT_rotate 120
#define MN_NXT_initPID 121
#define MN_NXT_basicStage 122

